import type { Case, Request, Document, DashboardStats, Notification, User } from "@/types";

export const mockUser: User = {
  id: "1",
  email: "attorney@counselintake.com",
  name: "James Mitchell",
  role: "attorney",
  firmId: "firm-1",
};

export const mockStaffUser: User = {
  id: "2",
  email: "staff@counselintake.com",
  name: "Sarah Chen",
  role: "staff",
  firmId: "firm-1",
};

export const mockStats: DashboardStats = {
  activeCases: 24,
  pendingRequests: 8,
  documentsThisWeek: 15,
  upcomingDeadlines: 5,
};

export const mockCases: Case[] = [
  {
    id: "c1",
    caseNumber: "2026-CV-0142",
    title: "Martinez v. Pacific Holdings LLC",
    clientName: "Elena Martinez",
    status: "discovery",
    assignedTo: "1",
    assignedToName: "James Mitchell",
    caseType: "Employment",
    courtDate: "2026-06-15",
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-04-08T14:30:00Z",
    notes: "Discovery responses due May 1. Deposition scheduled.",
  },
  {
    id: "c2",
    caseNumber: "2026-CV-0198",
    title: "Thompson v. Riverside Medical Group",
    clientName: "David Thompson",
    status: "active",
    assignedTo: "1",
    assignedToName: "James Mitchell",
    caseType: "Medical Malpractice",
    courtDate: "2026-08-22",
    createdAt: "2026-02-14T10:00:00Z",
    updatedAt: "2026-04-07T09:15:00Z",
    notes: "Expert retained. Awaiting medical records from third-party.",
  },
  {
    id: "c3",
    caseNumber: "2026-PI-0056",
    title: "Garcia v. Metro Transit Authority",
    clientName: "Rosa Garcia",
    status: "negotiation",
    assignedTo: "1",
    assignedToName: "James Mitchell",
    caseType: "Personal Injury",
    courtDate: null,
    createdAt: "2025-11-20T12:00:00Z",
    updatedAt: "2026-04-09T08:00:00Z",
    notes: "Demand letter sent. Settlement conference pending.",
  },
  {
    id: "c4",
    caseNumber: "2026-CV-0210",
    title: "Baker Estate v. National Insurance Co.",
    clientName: "Baker Estate",
    status: "intake",
    assignedTo: "2",
    assignedToName: "Sarah Chen",
    caseType: "Insurance",
    courtDate: null,
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-04-08T16:45:00Z",
    notes: "Initial documents collected. Conflict check complete.",
  },
  {
    id: "c5",
    caseNumber: "2025-CV-0891",
    title: "Williams v. Apex Construction",
    clientName: "Mark Williams",
    status: "litigation",
    assignedTo: "1",
    assignedToName: "James Mitchell",
    caseType: "Construction Defect",
    courtDate: "2026-05-10",
    createdAt: "2025-09-15T08:00:00Z",
    updatedAt: "2026-04-05T11:20:00Z",
    notes: "Trial prep in progress. Motion in limine filed.",
  },
  {
    id: "c6",
    caseNumber: "2026-CV-0175",
    title: "Nguyen v. TechStart Inc.",
    clientName: "Linh Nguyen",
    status: "active",
    assignedTo: "1",
    assignedToName: "James Mitchell",
    caseType: "Wrongful Termination",
    courtDate: "2026-09-30",
    createdAt: "2026-01-28T14:00:00Z",
    updatedAt: "2026-04-06T10:00:00Z",
    notes: "Complaint filed. Awaiting defendant's answer.",
  },
];

export const mockRequests: Request[] = [
  {
    id: "r1",
    title: "Draft discovery responses \u2014 Martinez case",
    description: "Prepare responses to defendant's first set of interrogatories and RFPs.",
    status: "in_progress",
    priority: "high",
    requestedBy: "1",
    requestedByName: "James Mitchell",
    assignedTo: "2",
    assignedToName: "Sarah Chen",
    caseId: "c1",
    caseTitle: "Martinez v. Pacific Holdings LLC",
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-04-08T14:00:00Z",
  },
  {
    id: "r2",
    title: "Request medical records \u2014 Thompson case",
    description: "Send records request to Riverside Medical and Dr. Park's office.",
    status: "pending",
    priority: "urgent",
    requestedBy: "1",
    requestedByName: "James Mitchell",
    assignedTo: null,
    assignedToName: null,
    caseId: "c2",
    caseTitle: "Thompson v. Riverside Medical Group",
    createdAt: "2026-04-07T11:00:00Z",
    updatedAt: "2026-04-07T11:00:00Z",
  },
  {
    id: "r3",
    title: "Prepare settlement demand package",
    description: "Compile medical records, bills, and draft demand letter for review.",
    status: "pending",
    priority: "high",
    requestedBy: "1",
    requestedByName: "James Mitchell",
    assignedTo: "2",
    assignedToName: "Sarah Chen",
    caseId: "c3",
    caseTitle: "Garcia v. Metro Transit Authority",
    createdAt: "2026-04-08T08:00:00Z",
    updatedAt: "2026-04-08T08:00:00Z",
  },
  {
    id: "r4",
    title: "Run conflict check \u2014 Baker Estate",
    description: "Full conflict check against all firm clients and opposing parties.",
    status: "completed",
    priority: "medium",
    requestedBy: "2",
    requestedByName: "Sarah Chen",
    assignedTo: "2",
    assignedToName: "Sarah Chen",
    caseId: "c4",
    caseTitle: "Baker Estate v. National Insurance Co.",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-02T15:00:00Z",
  },
  {
    id: "r5",
    title: "File motion in limine \u2014 Williams case",
    description: "E-file motion in limine and proof of service with the court.",
    status: "approved",
    priority: "urgent",
    requestedBy: "1",
    requestedByName: "James Mitchell",
    assignedTo: "2",
    assignedToName: "Sarah Chen",
    caseId: "c5",
    caseTitle: "Williams v. Apex Construction",
    createdAt: "2026-04-03T09:00:00Z",
    updatedAt: "2026-04-04T16:00:00Z",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "d1",
    name: "Complaint \u2014 Martinez v. Pacific Holdings.pdf",
    type: "application/pdf",
    size: 245000,
    caseId: "c1",
    caseTitle: "Martinez v. Pacific Holdings LLC",
    uploadedBy: "1",
    uploadedByName: "James Mitchell",
    category: "pleading",
    createdAt: "2026-01-10T08:30:00Z",
    updatedAt: "2026-01-10T08:30:00Z",
  },
  {
    id: "d2",
    name: "Defendant's Interrogatories Set 1.pdf",
    type: "application/pdf",
    size: 180000,
    caseId: "c1",
    caseTitle: "Martinez v. Pacific Holdings LLC",
    uploadedBy: "2",
    uploadedByName: "Sarah Chen",
    category: "discovery",
    createdAt: "2026-03-20T14:00:00Z",
    updatedAt: "2026-03-20T14:00:00Z",
  },
  {
    id: "d3",
    name: "Medical Records \u2014 Thompson.pdf",
    type: "application/pdf",
    size: 1200000,
    caseId: "c2",
    caseTitle: "Thompson v. Riverside Medical Group",
    uploadedBy: "2",
    uploadedByName: "Sarah Chen",
    category: "evidence",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "d4",
    name: "Expert Report \u2014 Dr. Williams.docx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 520000,
    caseId: "c2",
    caseTitle: "Thompson v. Riverside Medical Group",
    uploadedBy: "1",
    uploadedByName: "James Mitchell",
    category: "evidence",
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-04-05T09:00:00Z",
  },
  {
    id: "d5",
    name: "Settlement Demand Letter Draft.docx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 98000,
    caseId: "c3",
    caseTitle: "Garcia v. Metro Transit Authority",
    uploadedBy: "2",
    uploadedByName: "Sarah Chen",
    category: "correspondence",
    createdAt: "2026-04-08T16:00:00Z",
    updatedAt: "2026-04-09T08:00:00Z",
  },
  {
    id: "d6",
    name: "Motion in Limine \u2014 Williams.pdf",
    type: "application/pdf",
    size: 310000,
    caseId: "c5",
    caseTitle: "Williams v. Apex Construction",
    uploadedBy: "1",
    uploadedByName: "James Mitchell",
    category: "pleading",
    createdAt: "2026-04-03T10:00:00Z",
    updatedAt: "2026-04-03T10:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    message: "Discovery responses due in 22 days \u2014 Martinez case",
    type: "warning",
    read: false,
    createdAt: "2026-04-09T08:00:00Z",
  },
  {
    id: "n2",
    message: "Motion in limine filed successfully \u2014 Williams case",
    type: "success",
    read: false,
    createdAt: "2026-04-04T16:30:00Z",
  },
  {
    id: "n3",
    message: "New request pending approval: Medical records request",
    type: "action",
    read: false,
    createdAt: "2026-04-07T11:05:00Z",
  },
  {
    id: "n4",
    message: "Court date approaching: Williams v. Apex Construction \u2014 May 10",
    type: "warning",
    read: true,
    createdAt: "2026-04-01T08:00:00Z",
  },
];
