import { User, Case, Request, Document, Notification, DashboardStats } from "@/types";

export const mockUsers: User[] = [
  {
    id: "usr_001",
    email: "attorney@counselintake.com",
    firstName: "James",
    lastName: "Mitchell",
    role: "attorney",
    firmId: "firm_001",
  },
  {
    id: "usr_002",
    email: "staff@counselintake.com",
    firstName: "Sarah",
    lastName: "Chen",
    role: "staff",
    firmId: "firm_001",
  },
];

export const mockCases: Case[] = [
  {
    id: "case_001",
    title: "Martinez v. Pacific Holdings LLC",
    caseNumber: "2026-CV-0142",
    client: "Elena Martinez",
    type: "Employment",
    status: "discovery",
    assignedAttorney: "James Mitchell",
    courtDate: "2026-06-15",
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-04-05T00:00:00Z",
  },
  {
    id: "case_002",
    title: "Thompson v. Riverside Medical Group",
    caseNumber: "2026-CV-0198",
    client: "David Thompson",
    type: "Medical Malpractice",
    status: "active",
    assignedAttorney: "James Mitchell",
    courtDate: "2026-08-22",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "case_003",
    title: "Garcia v. Metro Transit Authority",
    caseNumber: "2026-PI-0056",
    client: "Rosa Garcia",
    type: "Personal Injury",
    status: "negotiation",
    assignedAttorney: "James Mitchell",
    courtDate: null,
    createdAt: "2025-11-20T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "case_004",
    title: "Baker Estate v. National Insurance Co.",
    caseNumber: "2026-CV-0210",
    client: "Baker Estate",
    type: "Insurance",
    status: "intake",
    assignedAttorney: "Sarah Chen",
    courtDate: null,
    createdAt: "2026-03-28T00:00:00Z",
    updatedAt: "2026-04-02T00:00:00Z",
  },
  {
    id: "case_005",
    title: "Williams v. Apex Construction",
    caseNumber: "2025-CV-0891",
    client: "Mark Williams",
    type: "Construction Defect",
    status: "litigation",
    assignedAttorney: "James Mitchell",
    courtDate: "2026-05-10",
    createdAt: "2025-08-14T00:00:00Z",
    updatedAt: "2026-04-04T00:00:00Z",
  },
  {
    id: "case_006",
    title: "Nguyen v. TechStart Inc.",
    caseNumber: "2026-CV-0175",
    client: "Linh Nguyen",
    type: "Wrongful Termination",
    status: "active",
    assignedAttorney: "James Mitchell",
    courtDate: "2026-09-30",
    createdAt: "2026-02-28T00:00:00Z",
    updatedAt: "2026-04-05T00:00:00Z",
  },
];

export const mockRequests: Request[] = [
  {
    id: "req_001",
    title: "Draft discovery responses — Martinez case",
    description: "Prepare responses to defendant's first set of interrogatories and RFPs.",
    caseId: "case_001",
    caseName: "Martinez v. Pacific Holdings LLC",
    status: "in_progress",
    priority: "high",
    requestedBy: "James Mitchell",
    assignedTo: "Sarah Chen",
    createdAt: "2026-04-05T00:00:00Z",
  },
  {
    id: "req_002",
    title: "Request medical records — Thompson case",
    description: "Send records request to Riverside Medical and Dr. Park's office.",
    caseId: "case_002",
    caseName: "Thompson v. Riverside Medical Group",
    status: "pending",
    priority: "urgent",
    requestedBy: "James Mitchell",
    assignedTo: null,
    createdAt: "2026-04-07T00:00:00Z",
  },
  {
    id: "req_003",
    title: "Prepare settlement demand package",
    description: "Compile medical records, bills, and draft demand letter for review.",
    caseId: "case_003",
    caseName: "Garcia v. Metro Transit Authority",
    status: "pending",
    priority: "high",
    requestedBy: "James Mitchell",
    assignedTo: "Sarah Chen",
    createdAt: "2026-04-08T00:00:00Z",
  },
  {
    id: "req_004",
    title: "Run conflict check — Baker Estate",
    description: "Full conflict check against all firm clients and opposing parties.",
    caseId: "case_004",
    caseName: "Baker Estate v. National Insurance Co.",
    status: "completed",
    priority: "medium",
    requestedBy: "Sarah Chen",
    assignedTo: "Sarah Chen",
    createdAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "req_005",
    title: "File motion in limine — Williams case",
    description: "E-file motion in limine and proof of service with the court.",
    caseId: "case_005",
    caseName: "Williams v. Apex Construction",
    status: "approved",
    priority: "urgent",
    requestedBy: "James Mitchell",
    assignedTo: "Sarah Chen",
    createdAt: "2026-04-03T00:00:00Z",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc_001",
    name: "Complaint — Martinez v. Pacific Holdings",
    category: "Pleading",
    caseId: "case_001",
    caseName: "Martinez v. Pacific Holdings LLC",
    uploadedBy: "James Mitchell",
    uploadedAt: "2026-01-12T00:00:00Z",
    fileSize: "245 KB",
  },
  {
    id: "doc_002",
    name: "Defendant's Answer — Martinez",
    category: "Pleading",
    caseId: "case_001",
    caseName: "Martinez v. Pacific Holdings LLC",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2026-02-15T00:00:00Z",
    fileSize: "189 KB",
  },
  {
    id: "doc_003",
    name: "Medical Records — Thompson (Riverside)",
    category: "Medical",
    caseId: "case_002",
    caseName: "Thompson v. Riverside Medical Group",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2026-03-20T00:00:00Z",
    fileSize: "1.2 MB",
  },
  {
    id: "doc_004",
    name: "Police Report — Garcia Accident",
    category: "Evidence",
    caseId: "case_003",
    caseName: "Garcia v. Metro Transit Authority",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2025-12-05T00:00:00Z",
    fileSize: "567 KB",
  },
  {
    id: "doc_005",
    name: "Motion in Limine — Williams",
    category: "Pleading",
    caseId: "case_005",
    caseName: "Williams v. Apex Construction",
    uploadedBy: "James Mitchell",
    uploadedAt: "2026-04-04T00:00:00Z",
    fileSize: "312 KB",
  },
  {
    id: "doc_006",
    name: "Demand Letter Draft — Garcia",
    category: "Correspondence",
    caseId: "case_003",
    caseName: "Garcia v. Metro Transit Authority",
    uploadedBy: "Sarah Chen",
    uploadedAt: "2026-04-06T00:00:00Z",
    fileSize: "98 KB",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif_001",
    message: "Discovery responses due in 22 days — Martinez case",
    type: "warning",
    read: false,
    createdAt: "2026-04-09T00:00:00Z",
  },
  {
    id: "notif_002",
    message: "Motion in limine filed successfully — Williams case",
    type: "success",
    read: false,
    createdAt: "2026-04-04T00:00:00Z",
  },
  {
    id: "notif_003",
    message: "New request pending approval: Medical records request",
    type: "info",
    read: false,
    createdAt: "2026-04-07T00:00:00Z",
  },
  {
    id: "notif_004",
    message: "Court date approaching: Williams v. Apex Construction — May 10",
    type: "urgent",
    read: true,
    createdAt: "2026-04-02T00:00:00Z",
  },
];

export const mockDashboardStats: DashboardStats = {
  activeCases: 24,
  pendingRequests: 8,
  documentsThisWeek: 15,
  upcomingDeadlines: 5,
};
